# Pipeline to create extension VSIX

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - tools/pipelines-tasks

pr: none

pool:
  name: 'msix-packaging-pool'

variables:
  tasksRoot: 'tools/pipelines-tasks'
  buildOutRoot: '$(Build.ArtifactStagingDirectory)/buildOutput'
  # Version number
  major: '1'
  minor: '1'
  patch: $[counter(variables['minor'], 0)]
  # Upload results of Semmle analysis
  LGTM.UploadSnapshot: true

steps:
- template: templates/build-steps.yml

